### ISSUE TITLE
Some issues on the UI

### ISSUE THREAD

**Issue by josethespecialist** [obahamonde/aiofauna#2]
There are some problems on the UI:

- Chats keeps rerendering.
- Message author is not defined on the chat container.
- Message Header doesn't show the proper contact picture.
- Chat List shows twice chat with yourself.

**Comment by obahamonde** [comment]
Hi @josethespecialist  I am working on the UI fixes right now just checking that.

**Comment by obahamonde** [comment]
I just pushed the changes, that partially solves the following:

- Consistency between application state and connections.
- Right ownership of each piece of content on the UI.

I will also add websockets later to the library so it can support more use cases. Thank you!
